services:
  node_app:
    container_name: node_app
    restart: always
    image : node_app_image 
    ports:
      - "3001:3001"
    links:
      - mongo:database
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  angular_app:
    container_name: angular_app
    restart: always
    image: angular_app_image
    ports:
      - "4200:80"
    links:
      - node_app
